fastcampus/fastcomponents

package.json
=> 0.0.0 으로 버전 변경

package.json
=> 0.0.1 버전으로 업데이트

playground/src/components/input-list.tsx, src/components/input.tsx, src/types/input.interface.ts, tsconfig.json
* 이모션 css 전달해서 스타일 지정하게 했던 것을 부모에서 className을 통해 css 정하게 하도록 수정
로컬 테스트
=> input 컴포넌트 이모션 타입 제거 (FCBPO-43)

package-lock.json, package.json
- 남은 경고는 아직 패치되지 않은 상태라 해소가 어려웠습니다.
O
=> misc: update packages

.github/workflows/check-build.yml, package-lock.json, package.json
=> misc: pr생성시 build 돌아가도록 workflow를 추가합니다.

.github/workflows/check-build.yml, package-lock.json, package.json
- react-router-dom v6 이상에서는 @types 불필요하여 제거합니다.
O
=> 0.0.3 release

playground/src/components/sort.tsx, playground/src/views/pagination/layout.tsx, src/components/sort/index.tsx, src/components/sort/sort.tsx, src/index.ts, src/types/sort.interface.ts
[FCLXP-66](https://fastcampus.atlassian.net/browse/FCLXP-66)
Sort 컴포넌트 추가
로컬 테스트
=> Sort 컴포넌트 추가 (FCLXP-66)

playground/src/components/checkbox.tsx, playground/src/views/home/layout.tsx, src/components/checkbox/checkbox.tsx, src/components/checkbox/index.tsx, src/index.ts, src/types/checkbox.interface.ts
[FCLXP-46](https://fastcampus.atlassian.net/browse/FCLXP-46)
체크박스 컴포넌트 추가
로컬 테스트
=> 체크박스 컴포넌트 추가 (FCLXP-46)

playground/src/components/radio.tsx, playground/src/views/home/layout.tsx, src/components/radio/index.tsx, src/components/radio/radio.tsx, src/index.ts, src/types/radio.interface.ts
[FCLXP-47](https://fastcampus.atlassian.net/browse/FCLXP-47)
Radio 컴포넌트 추가
로컬 테스트
=> Radio 컴포넌트 추가 (FCLXP-47)

src/components/calendar/date-calendar.tsx, src/components/checkbox/checkbox.tsx, src/components/pagination/pagination.tsx, src/components/radio/radio.tsx, src/components/select/select.tsx, src/components/sort/sort.tsx, src/components/table/table.tsx, src/types/calendar.interface.ts, src/types/checkbox.interface.ts, src/types/pagination.interface.ts, src/types/radio.interface.ts, src/types/select.interface.ts, src/types/sort.interface.ts, src/types/table.interface.ts
컴포넌트들에 className props 추가 
```typescript
<FCButton
css={css`
img {
margin-right: 1rem;
}
`}
onClick={() => (window.location.href = 'https://fastcampus.app')}
>
</FCButton>
```
처럼 컴포넌트에 emotion/css 로 스타일 주입하려면 className을 전달해주어야함
로컬 테스트
=> 컴포넌트들에 className props 추가

package-lock.json, package.json
=> misc: 사용하지 않는 패키지 제거

package-lock.json, package.json
=> v0.0.5 release

src/components/select/custom-select.tsx, src/components/select/native-select.tsx, src/types/select.interface.ts
* selected 사용하지 말라는 warning 제거
* custom-select 창 닫혔을 때 클릭되는 것 수정 
* setSelectAll optional 로 변경
로컬 테스트
=> select: selected 버그 수정

src/components/select/select.tsx
setSelectAll 있을때만 실행하도록 수정
로컬 테스트
=> select: setSelectAll 있을때만 실행하도록 수정

src/index.ts, src/types/input.interface.ts, tsconfig.json
다른 패키지에서 fastcomponents 사용할 때 
build시 index.d.ts 파일이 생성되지 않아 타입정보를 가져오지 못하는 것 수정
로컬 테스트
=> config: declaration 추가

src/components/calendar/date-calendar.tsx, src/components/calendar/date-input.tsx, src/components/calendar/utils.ts
=> calendar: 날짜 선택 기능 추가

playground/src/components/tab-list.tsx, playground/src/shared/routes/index.tsx, playground/src/views/home/layout.tsx, src/components/tab-list/index.tsx, src/components/tab-list/tabList.tsx, src/index.ts, src/types/tab-list.interface.ts
[FCLXP-86](https://fastcampus.atlassian.net/browse/FCLXP-86)
tab-list 컴포넌트 추가
로컬 테스트
=> tab-list 컴포넌트 추가 (FCLXP-86)

playground/src/components/tab-list.tsx, playground/src/shared/routes/index.tsx, playground/src/views/home/layout.tsx, src/components/calendar/date-calendar.tsx, src/components/calendar/date-input.tsx, src/components/calendar/utils.ts, src/components/tab-list/index.tsx, src/components/tab-list/tabList.tsx, src/index.ts, src/types/tab-list.interface.ts
* calendar 날짜선택기능 추가
* tab-list 추가
O
=> v0.0.7 release

README.md
=> doc: readme 패키지 설명 추가 

README.md, src/components/checkbox/checkbox.tsx
[checkbox label 클릭 stopPropagation 추가](https://github.com/fastcampus/fastcomponents/commit/791ea331182e7a8fa810bcbf548e4af6594c6b5b)
로컬 테스트
=> v0.0.8 release

playground/src/components/textarea.tsx, playground/src/views/home/layout.tsx, src/components/textarea/index.tsx, src/components/textarea/textarea.tsx, src/index.ts, src/types/textarea.interface.ts
[FCLXP-122](https://fastcampus.atlassian.net/browse/FCLXP-122)
* textarea 컴포넌트 추가
로컬테스트
=> textarea 컴포넌트 추가 (FCLXP-122)

src/components/input/input.tsx, src/components/textarea/textarea.tsx, src/types/input.interface.ts, src/types/textarea.interface.ts
* input, textarea id 추가
로컬 테스트
=> input, textarea id 추가

playground/src/components/pagination.tsx, playground/src/icons/first.svg, playground/src/icons/last.svg, playground/src/icons/next.svg, playground/src/icons/prev.svg, src/components/pagination/pagination.tsx, src/types/pagination.interface.ts
pagination 버튼이 자식 요소를 받을 수 있도록 수정했습니다.
=> v0.0.10 release

playground/src/App.tsx, playground/src/shared/routes/index.tsx, src/components/file-uploader/file-uploader.tsx, src/types/file-uploader.interface.ts
[FCLXP-156](https://fastcampus.atlassian.net/browse/FCLXP-156)
* 파일선택 버튼 문구 수정할 수 있도록 label로 버튼 대신하도록 수정
* playground에 navigation 바 추가
로컬 테스트
=> 파일업로더 버튼 label로 지정하도록 수정 (FCLXP-156)

playground/src/App.tsx, playground/src/shared/routes/index.tsx, src/components/file-uploader/file-uploader.tsx, src/types/file-uploader.interface.ts
* [Feat: 파일 업로드 버튼 label로 수정](https://github.com/fastcampus/fastcomponents/commit/a59e03faa229e823c62239836f69b230a2030549)
=> v0.0.11 release

playground/src/components/select.tsx, playground/src/views/home/layout.tsx, src/components/select/select.tsx, src/types/select.interface.ts
[FCLXP-193](https://fastcampus.atlassian.net/browse/FCLXP-193)
* select에 초기 값 넣도록 수정
로컬 테스트
=> select에 초기 값 주입하도록 수정 (FCLXP-193)

playground/src/components/select.tsx, playground/src/views/home/layout.tsx, src/components/select/select.tsx, src/types/select.interface.ts
=> v0.0.12 release

playground/src/components/file-uploader.tsx, src/components/checkbox/checkbox.tsx, src/components/file-uploader/file-uploader.tsx, src/types/checkbox.interface.ts, src/types/file-uploader.interface.ts
[FCLXP-196](https://fastcampus.atlassian.net/browse/FCLXP-196)
파일업로더 초기 파일 입력값 추가
로컬테스트
=> 파일업로더 초기 파일 입력값 추가 (FCLXP-196)

src/components/select/select.tsx
초기 값 변경시 selectValue 변경 하도록 수정
*  비동기로 받아오는 initialSelectedValue 가 적용되지 않음
로컬테스트
=> 초기 값 변경시 selectValue 변경 하도록 수정

playground/src/components/file-uploader.tsx, src/components/checkbox/checkbox.tsx, src/components/file-uploader/file-uploader.tsx, src/components/select/select.tsx, src/types/checkbox.interface.ts, src/types/file-uploader.interface.ts
* file-uploader, select 초기값 넣을 수 있는 기능 추가
=> v0.0.13 release 

.github/workflows/release-drafter.yml, src/components/select/custom-select.tsx, src/components/select/native-select.tsx, src/components/select/select.tsx, src/types/select.interface.ts
- select의 initial value가 부여되지 않았을 때 placeholder를 보여주도록 합니다.
=> v0.0.14 release

src/components/button/button.tsx, src/components/checkbox/checkbox.tsx, src/components/input/input.tsx, src/components/pagination/pagination.tsx, src/components/radio/radio.tsx, src/components/select/custom-select.tsx, src/components/select/native-select.tsx, src/components/select/select.tsx, src/components/sort/sort.tsx, src/components/tab-list/tabList.tsx, src/components/table/table.tsx, src/components/textarea/textarea.tsx
=> rest props를 받을 수 있도록 수정

src/components/button/button.tsx, src/components/checkbox/checkbox.tsx, src/components/input/input.tsx, src/components/pagination/pagination.tsx, src/components/radio/radio.tsx, src/components/select/custom-select.tsx, src/components/select/native-select.tsx, src/components/select/select.tsx, src/components/sort/sort.tsx, src/components/tab-list/tabList.tsx, src/components/table/table.tsx, src/components/textarea/textarea.tsx
=> v0.0.15 release

src/components/select/custom-select.tsx, src/components/select/native-select.tsx, src/types/input.interface.ts
- select의 className지정이 별도로 없어 미리 정의된 className이 override되어버리는 현상을 수정합니다.
- input ref의 type을 수정합니다.
=> v0.0.16 release

playground/src/components/bpo-calendar.tsx, playground/src/views/home/layout.tsx, src/components/calendar/calendar-contents.tsx, src/components/calendar/calendar.tsx, src/components/calendar/date-calendar.tsx, src/components/calendar/date-input.tsx, src/types/calendar.interface.ts
[FCLXP-157](https://fastcampus.atlassian.net/browse/FCLXP-157)
* navigate, input 사용하지 않는 기능 추가
* 달력 범위 선택 추가
* input으로 date, endDate 받아 사용하는 기능 추가
로컬 테스트
=> calendar 범위 선택, date 입력 받는 기능 추가 (FCLXP-157)

playground/src/components/bpo-calendar.tsx, playground/src/views/home/layout.tsx, src/components/calendar/calendar-contents.tsx, src/components/calendar/calendar.tsx, src/components/calendar/date-calendar.tsx, src/components/calendar/date-input.tsx, src/types/calendar.interface.ts
* 달력 범위선택기능 추가
* 기본 navigator, input disable 추가
=> v0.0.17 release

.github/workflows/npm-publish.yml
https://day1c.slack.com/archives/C01BY5C1QVB/p1648781026861279
publish workflow에서 check pusher제거
버전업 commit message에 ci skip 태그를 달아 이후 워크 플로우 작동 안되도록 방지
=> publish workflow에서 check pusher제거

package-lock.json, playground/src/components/select.tsx, playground/src/views/home/layout.tsx, src/components/select/custom-select.tsx, src/components/select/native-select.tsx, src/components/select/select.tsx, src/types/button.interface.ts, src/types/select.interface.ts
[FCLXP-247](https://fastcampus.atlassian.net/browse/FCLXP-247)
* value를 props로 받아 부모 컴포넌트의 값이 바뀌었을 때 select 의 값이 바뀌어야 하는 것 구현 가능하도록 수정
* select open시 css 변경할 수 있게 .open 추가
* disabled props 추가
bpo에서 불러와 사용할 때 잘 동작하는 것 확인
=> select value, disabled props추가, open 시 className 추가

playground/src/components/calendar.tsx, src/components/calendar/calendar.tsx, src/components/calendar/date-calendar.tsx, src/components/calendar/date-input.tsx, src/types/calendar.interface.ts
기존 
수정 
* 달력 날짜 클릭시 하루 앞 날짜가 선택되는 버그 수정
로컬 테스트
=> 달력 날짜 클릭시 하루 앞 날짜 선택되는 버그 수정

playground/src/components/player.tsx, src/components/player/kollus.tsx
FCLXP-395
- iframe src가 변경 되었을 때, 변경된 iframe src의 vgController 인스턴스를 생성하고 이벤트를 설정합니다.
=> feat: player src change effect(FCLXP-395)

package-lock.json, package.json, playground/src/shared/routes/index.tsx, playground/src/views/charts/layout.tsx, src/components/charts/pie/index.ts, src/components/charts/pie/pie-chart.tsx, src/index.ts, src/types/charts.interface.ts
FCLXP-589
https://user-images.githubusercontent.com/57934965/175469116-811ccea4-9933-4f97-9430-ddda99d1bffe.mov
- ant chart를 사용한 pie chart구현
- 추후 범용적인 props interface를 정의하여 라이브러리와 커플링이 최소화 되도록 해야함.
O
=> Feature/pie chart (FCLXP-589)

src/components/select/select.tsx
* select value 값에 0을 넣었을 때 값을 초기화해버리는 버그 수정
로컬 테스트
=> select: value 값이 falsy값 중 undefined, null NaN 일 때만 초기화하도록 수정

playground/src/components/textarea.tsx, src/components/textarea/textarea.tsx, src/types/textarea.interface.ts
textarea의 resize 기능을 위해서, key event handler가 필요합니다.
- textarea > keyboard event handler 추가
- onKeyDown
- onKeyPress
- onKeyUp
=> feat: textarea keyboard event handler 추가
